/**** Tratando de erros *****/

try {
    console.log(varInexistente);
} catch (err) {
    console.log ('varInexistente n√£o existe');
}